<?php include  __DIR__ . '/header.phtml' ?>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= $data['urlData']['name'] ?></h1>
            <div class="table-responsive mb-5">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $data['urlData']['id'] ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $data['urlData']['name'] ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $data['urlData']['created_at'] ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mb-3">Проверки</h2>
            <form class="mb-2" method="post" action="/urls/<?= $data['urlData']['id'] ?>/checks">
                <input type="submit" class="btn btn-primary " value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><?= $urlData['id'] ?></td>
                    <td>200</td>
                    <td>...</td>
                    <td>...</td>
                    <td>...</td>
                    <td><?= $urlData['created_at'] ?></td>
                </tr>
                </tbody>
            </table>
        </div>
    </main>

<?php include  __DIR__ . '/footer.phtml' ?>