 <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= htmlspecialchars($data['urlData']['name']) ?></h1>
            <div class="table-responsive mb-5">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $data['urlData']['id'] ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($data['urlData']['name']) ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= htmlspecialchars($data['urlData']['created_at']) ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mb-3">Проверки</h2>
            <form class="mb-2" method="post" action="<?= $router->urlFor('urls.check', ['id' => $data['urlData']['id']])?>">
                <input type="submit" class="btn btn-primary " value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($urlCheckData as $urlCheck): ?>
                <tr>
                    <td><?= $urlCheck['id'] ?></td>
                    <td><?= $urlCheck['status_code'] ?></td>
                    <td><?= htmlspecialchars($urlCheck['h1']) ?></td>
                    <td><?= htmlspecialchars($urlCheck['title']) ?></td>
                    <td><?= htmlspecialchars($urlCheck['description']) ?></td>
                    <td><?= $urlCheck['created_at'] ?></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </main>
